name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: root
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: simple_bank
        ports:
          - 5432:5432
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s 
          --health-retries 5

    steps:

      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
        id: go

      - name: checkout code
        uses: actions/checkout@v4

      - name: Install migrate tool
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.2/migrate.linux-amd64.tar.gz | tar xvz
          sudo mv migrate /usr/bin/migrate
          sudo chmod +x /usr/bin/migrate
          which migrate

      - name: run migration
        run: make migrateup
      
      - name: test
        run: make test